server:
  port: 8023

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8021"
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/hotels/**,/staffs/**
        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=/ratings/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/