#server:
 # port: 8028

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservice

  application:
    name: rating-service


#eureka:
 # client:
  #  service-url:
   #   defaultZone: http://localhost:8761/eureka/
  config:
    import: "optional:configserver:http://localhost:8021"


