server:
  port: 8021

spring:
  profiles:
    active: native

#spring:
 # application:
  #  name: config-server
  #cloud:
   # config:
    #  server:
     #   git:
      #    uri: https://github.com/Praveenreddy23/MicroService_Cinfig-Server/tree/main
       #   clone-on-start: true



